### ISSUE TITLE
Getting true RR interval sequence from smartwatch data.

### ISSUE THREAD

**Issue by filby89** [PGomes92/pyhrv#14]
Hi and thank you very much for your extremely helpful toolbox. I have data from a smartwatch (Gear S3) obtained at 5Hz. The data consists of the Timestamp of each sample, the beats per minute, and the RRinterval of the last detected pulse (Image)

![image](https://user-images.githubusercontent.com/9838129/70852733-9a973e00-1ead-11ea-9403-e431694c4a84.png)

Due to the fact that the signal is sampled at 5Hz, if a new pulse has not been detected then we get the same value multiple times as can be seen in the Figure. One quick way to get the true RRI series would be to drop consecutive values, however we have seen many cases where the output of the watch is the same for a long period (e.g. 5 seconds). We do not know if its because the watch hasn't detected a new pulse, or if the rRInterval detected is exactly the same with the previous. 

Do you know if there is a better way/algorithm to extract/approximate the true sequence (apart from dropping consecutive values or some of them) ? Thanks!

**Comment by PGomes92** [comment]
HI @filby89,

thanks for considering pyHRV. 

Unfortunately, as this is not related to pyHRV and as I am not familiar with the system I can only provided limited help. However, I would recommend using another heart rate detection device, ideally a single channel ECG, in parallel to 'benchmark' the device you're using to check you are getting reliable data or not. At least I don't see it as a viable option to backwards engineer a heart rate from the repetitive data you shared.

Hope this helps!
