### ISSUE TITLE
nonlinear.poincare - show=False Attribute does not work 

### ISSUE THREAD

**Issue by salpers** [PGomes92/pyhrv#15]
pyhrv.nonlinear.poincare(nni = data, show=False) seems to not disable the visual output. 
Is there any other way to disable the visualization?

**Comment by NotrinoResearch** [comment]
The problem persists. Have you ever solved this issue?

**Comment by andreazignoli** [comment]
This was true for `hdfa` plot also. But after reading the code I think that the following is happening: the package calls `matplotlib` and then `if show` it calls `plt.show()`. This means that in debugging modality you'll see plots, but when you `run` with `show=False` you won't see them. At least, this is what is happening to me.

**Comment by PGomes92** [comment]
Hi at all! 

thanks for using pyHRV! 

When pyHRV runs functions with plotting features it always generates a plot figure. The show=False parameter only hides the plot figure. 

In some cases, depending on the working environment, when calling matplotlib's `plot.show()` at another point in your code, matplotlib will show all available plot figures. This includes showing also any available pyHRV plot figure.

Some functions (primarily the Frequency Domain functions) already come with a 'normal' mode which results with the known behavior, but also have an additional 'dev' mode where only the output data is computed an now plot is generated at all.

I am considering adding this option also to the nonlinear functions. For this reason, I am reopening this issue until the changes come with the next update.
