### ISSUE TITLE
during report generation found error

### ISSUE THREAD

**Issue by BHAVIN912** [PGomes92/pyhrv#17]
pyhrv.report.hrv_report(results, path='C:\ecgt\pyhrvwork', rfile='SampleReport', file_format='csv')

AttributeError: module 'pyhrv' has no attribute 'report'

pyhrv.tools.hrv_report(results, rfile='SampleReport', path='/my/favorite/path/')

same error found in both type of syntax

help me out

**Comment by JacquelineBorgstedt** [comment]
Did you manage to solve the error? I have the same problem and cannot fix it

**Comment by PGomes92** [comment]
@JacquelineBorgstedt thanks for clarifying, I didn't have the opportunity to do it earlier.

The restructure was necessary to organise the content for the LaTeX PDF report feature. Sorry for the confusion!
