### ISSUE TITLE
Does the Python HRV toobox work with the HR & HRV Logger per Polar H6, H7, H10 e OH1 app?

### ISSUE THREAD

**Issue by PeterGamma** [PGomes92/pyhrv#21]
The Polar OH1 optical heart rate sensor has ECG accuracy:

https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0217288

and R-R peaks in the sensor stream:

https://towardsdatascience.com/creating-a-data-stream-with-polar-device-a5c93c9ccc59

Furthermore, the Polar OH1 is comfortable to wear and affordable. Sensor data can be obtained with the HR & HRV Logger per Polar H6, H7, H10 e OH1 app:

https://play.google.com/store/apps/details?id=hrmonitor.com.hr_rri_monitor&gl=CH

but does this app also work with the Python HRV toolbox?

**Comment by PGomes92** [comment]
Hi @PeterGamma,

thanks for using pyHRV! I am picking up on these pending topics again, and although I imagine that your question has been solved in the meantime, I'd still like to close these questions.

As far as I can see, the HR & HRV Logger is capable of exporting the raw RR-Interval Series into a .CSV file. In this case, you can open this file in Python and use the provided input data to work with pyHRV. Hope it helps!

**Comment by PeterGamma** [comment]
Thanks, Pedro, yes it helps!
