### ISSUE TITLE
Samples folder contains no files

### ISSUE THREAD

**Issue by bdekoven** [PGomes92/pyhrv#26]
FYI - the samples folder does not contain any files.

Thank you.

![image](https://user-images.githubusercontent.com/9664571/120078781-f9cb1d00-c065-11eb-8633-6d82d0e1c6be.png)

**Comment by PGomes92** [comment]
Hi @bdekoven,

thanks for using pyHRV! 

The sample files from this database have been removed and replaced by some simpler sample files which are now available here:

https://github.com/PGomes92/pyhrv/tree/master/pyhrv/files

I will correct the documentation with the next update.
