### ISSUE TITLE
LSL/XDF data to PyHRV

### ISSUE THREAD

**Issue by sunshineinsandiego** [PGomes92/pyhrv#27]
Hi - I'm working with a Polar H10 heart rate monitor, and I'm wondering if it's possible to use this device with PyHRV. I can pipe the H10 into LSL and save as an XDF, but trying to understand if you've seen anyone analyze data off a Polar monitor using this tool. Thanks!

** Update **
So it seems as if this is not possible. Trying to use PyHRV in a real-time context appears challenging because the module relies on an OpenSignals ECG txt file as input. Converting a real-time stream into an OpenSignals text file and then porting that back into PyHRV probably too much overhead for real-time use. 

Which brings me to another question, is there any way to use the PyHRV functions on numpy arrays? The data I read off a polar monitor is pretty simple (timestamp and microvoltage), and it would be great to be able to feed the voltage data +/- the sampling frequency (130hz) into PyHRV for real-time analysis without needing to convert each data chunk into a text file for processing.

**Comment by PGomes92** [comment]
Hi @sunshineinsandiego, 

thanks for using pyHRV. You have most likely already solved this issue but as I am picking up on this project again after a long break, I'd like to share here some input.

pyHRV is not designed for real-time signal processing, but rather for post-processing of acquired R-Peak-to-R-Peak Interval (RRI) series. Real-time processing could technically be achieved with some simple HRV parameter computations, but from my experience the heavier functions (e.g. frequency domain) are too slow to be useful in real-time processing.

Also, it is important to highlight that **pyHRV runs any RRI series in bumpy array format and is not exclusive to OpenSignals files**. The examples provided with OpenSignals are only available as it was the software I used to record signals and test pyHRV during my thesis. With this being said, allow to answer your questions below:

> Which brings me to another question, is there any way to use the PyHRV functions on numpy arrays?
Yes, this is perfectly possible and there are a few examples available in the Quickstart guide using the time domain functions here:

https://github.com/PGomes92/pyhrv/tree/master/pyhrv

If you already have a RRI series (or NNI) in an numpy array, it's quite straightforward to use it with pyHRV as shown in the example below:

```
# Import packages
import numpy as np
import pyhrv.time_domain as td 

# Load NNI sample series
nni = np.load('./files/SampleNNISeries.npy')

# Compute SDNN
result = td.sdnn(nni)

# Access SDNN value using the key 'sdnn'
print(result['sdnn'])
```

> Polar input Data
If the Polar monitor provides you a full ECG in mV, the data must first be processed to run with pyHRV as you need to extract the heart rate series our RRI/NNI series from the ECG first. 

For this, you can generally follow the same tutorial that's available for OpenSignals input data:

```
import biosppy
import numpy as np
import pyhrv.tools as tools

# Load sample ECG signal 
signal = your_signal # <- this should be your ECG signal in mV

# Get R-Peak locations from ECG signal
rpeaks = biosppy.signals.ecg.ecg(signal, show=False)[2]

# Compute NNI
nni = tools.nn_intervals(rpeaks)

# Compute SDNN
result = td.sdnn(nni)
```

Hope this information is still useful for anyone who comes across this issue and feels free to let me know if you have any questions.
