### ISSUE TITLE
Plot Tachogram Error

### ISSUE THREAD

**Issue by cogitoxin** [PGomes92/pyhrv#28]
When I try to plot tachogram I get this error, please help.

 tools.tachogram(signal, interval=[0, 15])
 
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-105-aca4abbabf47> in <module>
      1 # Plot the Tachogram of the ECG signal (interval: 0s to 15s)
----> 2 tools.tachogram(signal, interval=[0, 15])

/opt/miniconda3/lib/python3.7/site-packages/pyhrv/tools.py in tachogram(nni, signal, rpeaks, sampling_rate, hr, interval, title, figsize, show)
    373                 interval = [0, t[-1]]
    374         else:
--> 375                 interval = pyhrv.utils.check_interval(interval, limits=[0, t[-1]], default=[0, 10])
    376 
    377         # Prepare figure

/opt/miniconda3/lib/python3.7/site-packages/pyhrv/utils.py in check_interval(interval, limits, default)
    228                 limits = default
    229         elif limits is not None:
--> 230                 limits = _check_limits(limits, 'limits')
    231 
    232         # Check interval limits

/opt/miniconda3/lib/python3.7/site-packages/pyhrv/utils.py in _check_limits(interval, name)
    283                 interval[0], interval[1] = interval[1], interval[0]
    284                 vals = (name, name, interval[0], interval[1])
--> 285                 warnings.warn("Corrected invalid '%s' limits (lower limit > upper limit).'%s' set to: %s" % vals)
    286         if interval[0] == interval[1]:
    287                 raise ValueError("'%f': Invalid interval limits as they are equal." % name)

TypeError: not all arguments converted during string formatting

**Comment by PGomes92** [comment]
Hi @cogitoxin,

thanks for using pyHRV! 

I have caught the issue which was causing an error in the warning and error descriptions which this functions generates, which eventually (and ironically) was triggering this error.

This will be fixed with the next update, but if you want to go ahead and copy paste the corrected version of this function, feel free to use this one:

```
def _check_limits(interval, name):
	"""Checks if interval limits are not overlapping or equal.

	Parameters
	----------
	interval : array, 2-element
		Interval boundaries [min, max].
	name : str
		Variable name to be used on exceptions and warnings.

	Returns
	-------
	interval : array, 2-element
		Valid and corrected interval limits (if correction is necessary).

	Raises
	------
	ValueError
		If interval limits are equal.

	Warnings
	--------
	..	If limits are overlapping (e.g. lower limit > upper limit) and had to be fixed.

	"""
	# upper limit < 0 or upper limit > max interval -> set upper limit to max
	if interval[0] > interval[1]:
		interval[0], interval[1] = interval[1], interval[0]
		warnings.warn("The provided lower limit of the parameter '%s' is greater than the upper limit. Limits have been switched." % name)
	if interval[0] == interval[1]:
		raise ValueError("The provided lower and upper limits of the parameter '%s' are invalid as they are identical." % name)
	return interval
```
