### ISSUE TITLE
pyhrv.hrv doest stop plotting

### ISSUE THREAD

**Issue by roohy466** [PGomes92/pyhrv#31]
Hi , 

I am trying to stop plotting from **pyhrv.hrv(show=False)** but it does not work and shows all the plots! I am using 0.4 version

**Comment by mosh-shu** [comment]
Same problem here, but solved!
When you look at the `_plot_psd` function in the `frequency_domain` module which you can inspect [here](https://github.com/PGomes92/pyhrv/blob/master/pyhrv/frequency_domain.py), `plot=False` option only gets applied to the last line of `if show: plt.show()`. However, in Jupyter notebook with the `%matplotlib inline` option called, `plt.show()` gets called at every cell anyway, so the show=False wouldn't mean anything. The workaround is to 1) not call the `%matplotlib inline` magicword in your notebook or 2) use the mode='dev' option to not produce the figure.

**Comment by PGomes92** [comment]
Hi @roohy466,

thanks for using pyHRV! 

As @mosh-shu has evaluated correctly (thanks for that btw!), when pyHRV runs functions with plotting features in 'normal' mode it always generates a plot figure. 

Although pyhrv.hrv(show=False) would normally generate a plot figurebut not showing it, your current project or setup might be calling matplotlib to show all the available plot figures at another point hence the reasons why your plots may appear.

If you want to prevent pyHRV from generating any plot figures at all, I'd recommend using the 'dev' mode as @mosh-shu suggested.

Thanks!
