### ISSUE TITLE
Can't build pyhrv wheel on Windows 10

### ISSUE THREAD

**Issue by snowuyl** [PGomes92/pyhrv#33]
D:\pyhrv>python3 setup.py bdist_wheel
Library mydpss not found
Traceback (most recent call last):
  File "D:\pyhrv\setup.py", line 8, in <module>
    long_description = fh.read()
UnicodeDecodeError: 'cp950' codec can't decode byte 0xe2 in position 3044: illegal multibyte sequence

**Comment by PGomes92** [comment]
Hi @snowuyl,

thanks for alerting about this issue. 

I currently don't have access to a Win10 PC to test it, but it appears to me that it could be an issue with the encoding of the file that setup.py is trying to open in line 7 & 8.

I would suggest changing line 7 from

`with open("README.md", "r") as fh:`

to this line instead 

`with open("README.md", "r", encoding="utf-8") as fh:`

Do you have the chance to test this fix and share some feedback?

**Comment by snowuyl** [comment]
No UnicodeDecodeError issue after changing line 7 of setup.py to 
with open("README.md", "r", encoding="utf-8") as fh:
