### ISSUE TITLE
default binsize for triangular_index() and tinn() should be 7.8125 instead of 7.815

### ISSUE THREAD

**Issue by gouzhuang** [PGomes92/pyhrv#4]
in triangular_index() and tinn(), the default value for binsize was set to 7.815, however the correct value should be 7.8125(1000/128).

**Comment by PGomes92** [comment]
You're absolutely right. I had the correct bin size of 7.815 in the docstring, but had the typo in the input parameters. I just updated the file and fixed that error. 

Many thanks for pointing it out!
