### ISSUE TITLE
Incorrect Documentation

### ISSUE THREAD

**Issue by CodeSeeker99** [PGomes92/pyhrv#6]
In the time domain documentation (**time.rst**)
The output **keys** mentioned for **triangular_index** are incorrect. They are given as 'tinn_histogram','tinn'....etc
**While they should be
'tri_histogram', 'tri_index'**

Goal:
[ ] Fixing Documentation

**Comment by PGomes92** [comment]
Thanks for pointing that out! You are absolutely right, I will correct this issue with the next update which should come soon.
